---
name: Schedule - Keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/scheduled-keepalive.yaml"

jobs:
  keepalive:
    name: Renovate
    uses: bjw-s/gh-workflows/.github/workflows/keepalive.yaml@main
    permissions:
      contents: write
    secrets:
      app_id: ${{ secrets.BJWS_APP_ID }}
      app_private_key: ${{ secrets.BJWS_APP_PRIVATE_KEY }}
